# Generated by Django 3.2.5 on 2021-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=64)),
                ('username', models.TextField(max_length=30, unique=True)),
                ('address', models.TextField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
